# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 16:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Define the supplier's name", max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='Set a debit account', on_delete=django.db.models.deletion.CASCADE, to='finances.FinAccount')),
                ('supplier', models.ForeignKey(help_text='Choose the supplier or add one', on_delete=django.db.models.deletion.CASCADE, to='warehouse.Supplier')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
                'verbose_name_plural': 'supplies',
            },
        ),
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('product', models.ForeignKey(help_text='Select product/ingredient', on_delete=django.db.models.deletion.CASCADE, to='menu.Product')),
                ('supply', models.ForeignKey(blank=True, help_text='Add related supply', null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.Supply')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('name', models.CharField(help_text='Specify the warehouse name', max_length=55)),
                ('address', models.TextField(help_text='Add address', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Warehouse')),
            ],
            options={
                'ordering': ['-date_created'],
                'verbose_name_plural': 'write_offs',
            },
        ),
        migrations.CreateModel(
            name='WriteOffItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('product', models.ForeignKey(help_text='Select product/ingredient', on_delete=django.db.models.deletion.CASCADE, to='menu.Product')),
                ('write_off', models.ForeignKey(blank=True, help_text='Add related Write off from warehouse', null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.WriteOff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='supply',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.Warehouse'),
        ),
    ]
