# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20160211_2215'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('arrival_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True)),
                ('product', models.ForeignKey(help_text='Select product/ingredient', null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Product')),
                ('supply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.Supply')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.Warehouse')),
            ],
        ),
        migrations.RemoveField(
            model_name='supplyitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='supplyitem',
            name='supply',
        ),
        migrations.RemoveField(
            model_name='writeoff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='writeoff',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='writeoffitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='writeoffitem',
            name='write_off',
        ),
        migrations.DeleteModel(
            name='SupplyItem',
        ),
        migrations.DeleteModel(
            name='WriteOff',
        ),
        migrations.DeleteModel(
            name='WriteOffItem',
        ),
    ]
