# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplyitem',
            old_name='order',
            new_name='supply',
        ),
        migrations.AlterField(
            model_name='supplyitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=9),
        ),
    ]
