# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 17:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0002_auto_20160211_2215'),
        ('warehouse', '0002_auto_20160211_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.Warehouse')),
            ],
            options={
                'ordering': ['-date_created'],
                'verbose_name_plural': 'write_offs',
            },
        ),
        migrations.CreateModel(
            name='WriteOffUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('init_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True)),
                ('product', models.ForeignKey(help_text='Select product/ingredient', null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Product')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.Warehouse')),
                ('write_off', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.WriteOff')),
            ],
        ),
    ]
