# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_writeoff_writeoffunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeoffunit',
            name='cost',
        ),
    ]
