# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20160113_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyitem',
            name='supply',
            field=models.ForeignKey(blank=True, help_text='Add related supply', null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.Supply'),
        ),
    ]
