# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0004_remove_writeoffunit_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Sell point name', max_length=128)),
                ('address', models.CharField(max_length=50, null=True)),
                ('terminal_login', models.CharField(blank=True, max_length=50, null=True)),
                ('warehouses', models.ManyToManyField(blank=True, null=True, to='warehouse.Warehouse')),
            ],
        ),
    ]
