# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Specify product/ingredient name', max_length=128)),
                ('type', models.CharField(choices=[('good', 'Good'), ('ingredient', 'Ingredient'), ('service', 'Service')], max_length=50, null=True)),
                ('measure_units', models.CharField(blank=True, choices=[('pcs.', 'pieces'), ('l', 'liter'), ('kg', 'kilogram'), ('box', 'box'), ('set', 'set')], help_text='Choose the measure units', max_length=5, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('barcode', models.CharField(blank=True, max_length=15, null=True)),
                ('if_discountable', models.NullBooleanField(default=True)),
                ('price', models.ManyToManyField(blank=True, null=True, to='menu.Price')),
            ],
        ),
    ]
