# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='if_discountable',
            field=models.NullBooleanField(),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
