# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measure_units',
            field=models.CharField(choices=[('pcs.', 'pieces'), ('l', 'liter'), ('kg', 'kilogram'), ('box', 'box'), ('set', 'set')], help_text='Choose the measure units', max_length=5),
        ),
    ]
