# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarter', '0001_initial'),
        ('menu', '0002_auto_20160211_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True)),
                ('markup', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Product')),
                ('sell_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headquarter.SellPoint')),
            ],
        ),
    ]
