# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_productprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='cost',
        ),
    ]
