# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('currency', models.CharField(max_length=3)),
                ('type', models.CharField(choices=[(1, 'Cash'), (2, 'Cashless'), (3, 'Bank Card')], max_length=1)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
        ),
    ]
