# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('headquarter', '0002_auto_20160306_1924'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_opened', models.DateTimeField(auto_created=True)),
                ('datetime_closed', models.DateTimeField(verbose_name='Specify date and time for closing cash shift')),
                ('is_closed', models.BooleanField(default=False)),
                ('cash_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('encashment', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('sell_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headquarter.SellPoint')),
            ],
        ),
        migrations.CreateModel(
            name='FinCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finances.FinCategory')),
            ],
            options={
                'verbose_name': 'fin_category',
                'verbose_name_plural': 'fin_categories',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('trans_type', models.CharField(choices=[(1, 'Revenue'), (2, 'Waste'), (3, 'Transfer')], max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('comment', models.CharField(max_length=1024)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.FinCategory')),
                ('fin_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.FinAccount')),
            ],
        ),
    ]
