# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaccount',
            name='currency',
            field=models.CharField(choices=[(980, 'UAH'), (810, 'RUR'), (974, 'BYR'), (840, 'USD')], max_length=3),
        ),
    ]
