# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_cashshift_fincategory_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashshift',
            name='datetime_opened',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
