# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20160113_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaccount',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(980, 'UAH'), (810, 'RUR'), (974, 'BYR'), (840, 'USD')], max_length=3),
        ),
        migrations.AlterField(
            model_name='finaccount',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Cash'), (2, 'Cashless'), (3, 'Bank Card')], max_length=1),
        ),
    ]
