# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_auto_20160307_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashshift',
            name='datetime_closed',
            field=models.DateTimeField(blank=True, verbose_name='Specify date and time for closing cash shift'),
        ),
    ]
