# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_auto_20160307_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_type',
            field=models.CharField(choices=[('revenue', 'Revenue'), ('waste', 'Waste'), ('transfer', 'Transfer')], max_length=24),
        ),
    ]
